# GitHub Issue Template for Feature Requests

name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: dropdown
    id: work_package
    attributes:
      label: Related Work Package
      description: Which work package is this feature related to?
      options:
        - WP1: Core Platform Infrastructure
        - WP2: User Authentication & Authorization
        - WP3: Profile Management
        - WP4: Content Management
        - WP5: Verification System
        - WP6: Persona Trait System
        - WP7: Output Format Generator
        - WP8: Content Distribution
        - WP9: Career Interview System
        - WP10: Analytics Engine
        - WP11: Frontend Implementation
        - Other/Not Sure
    validations:
      required: true
